import type { ClansData } from '../types'

// Sources: the official "Hoja de Clanes" reference sheet (nickname, verbs,
// Disciplines, Bane and Compulsion names) plus the V5 corebook, Camarilla,
// Anarch and Companion rules for the Bane/Compulsion mechanics.
//
// Clans are listed in the sheet's own order (alphabetical in Spanish).
// Discipline ids match src/content/disciplines.ts, `oblivion` included.
export const CLANS_DATA: ClansData = {
  clans: [
    {
      id: 'banu-haqim',
      name: 'Banu Haqim',
      nickname: 'Los Jueces',
      verbs: ['adjudicar', 'castigar', 'disciplinar', 'ejecutar', 'juzgar'],
      description: 'Guerreros y eruditos a partes iguales, los Banu Haqim juzgan a los suyos con una vara que la mayoría de los Vástagos considera intolerable. Durante siglos vivieron apartados de la Camarilla, vendiendo sus servicios como asesinos; hoy muchos han jurado lealtad a la Torre de Marfil sin renunciar a su sed de justicia. Su Sangre los empuja a beber de quienes quebrantan sus Convicciones.',
      disciplines: ['blood-sorcery', 'celerity', 'obfuscation'],
      bane: {
        name: 'Adicción a la Sangre',
        description: 'Cuando un Banu Haqim sacia al menos un nivel de Ansia con la sangre de otro vampiro, debe superar una tirada de Frenesí de hambre a dificultad 2 + Severidad de la Prohibición. Si falla, se ceba con la vitae y se abre la puerta a una posible Amaranto.',
      },
      compulsion: {
        name: 'Juicio',
        description: 'El vampiro se ve impelido a castigar a quien obra mal: debe saciar al menos un nivel de Ansia de cualquiera que actúe contra sus propias Convicciones. Mientras no lo haga sufre −3 dados en todas sus reservas, hasta que lo consiga o termine la escena.',
      },
      color: '#9c2b3d',
      colorDark: '#5a1722',
      colorGlow: 'rgba(156,43,61,0.4)',
    },
    {
      id: 'brujah',
      name: 'Brujah',
      nickname: 'Los Rebeldes',
      verbs: ['luchar', 'oponer', 'protestar', 'rebelarse', 'resistir'],
      description: 'Idealistas con los colmillos apretados. Los Brujah fueron filósofos y guerreros-poetas antes de convertirse en el motor de casi todas las revueltas de la noche. Arden de rabia contra cualquier autoridad que consideren injusta, y esa misma rabia es lo que los consume: pocos clanes tienen tan a flor de piel a la Bestia.',
      disciplines: ['celerity', 'potence', 'presence'],
      bane: {
        name: 'Temperamento violento',
        description: 'La furia hierve siempre bajo la superficie. Resta un número de dados igual a la Severidad de la Prohibición a cualquier tirada para resistir un Frenesí de furia.',
      },
      compulsion: {
        name: 'Rebelión',
        description: 'El Brujah debe desafiar a una figura de autoridad, contradecir lo que se espera de él o hacer cambiar de opinión a alguien. Hasta que lo logre sufre −2 dados en todas sus reservas.',
      },
      color: '#c4472e',
      colorDark: '#722416',
      colorGlow: 'rgba(196,71,46,0.4)',
    },
    {
      id: 'gangrel',
      name: 'Gangrel',
      nickname: 'Las Bestias',
      verbs: ['acechar', 'aguantar', 'cambiar de forma', 'luchar', 'merodear'],
      description: 'Nómadas, supervivientes y solitarios. Los Gangrel están más cerca de la Bestia que ningún otro Vástago y no lo consideran una maldición sino una ventaja: cambian de forma, corren con los lobos y duermen bajo tierra. Cuanto más viejos se hacen, menos queda en ellos de lo humano.',
      disciplines: ['animalism', 'fortitude', 'protean'],
      bane: {
        name: 'Rasgos bestiales',
        description: 'Al entrar en Frenesí, el Gangrel gana tantos rasgos animales como su Severidad de la Prohibición. Cada rasgo resta 1 punto a un Atributo y persiste hasta la noche siguiente. Cabalgar la Ola limita la manifestación a un único rasgo y una sola pérdida.',
      },
      compulsion: {
        name: 'Impulsos animales',
        description: 'El vampiro retrocede a un estado animal: durante una escena sufre −3 dados en toda tirada que use Manipulación o Inteligencia y solo puede expresarse con frases de una palabra.',
      },
      color: '#6d8241',
      colorDark: '#3c4a21',
      colorGlow: 'rgba(109,130,65,0.4)',
    },
    {
      id: 'hecata',
      name: 'Hécata',
      nickname: 'Los Necromantes',
      verbs: ['documentar', 'investigar', 'invocar y atar fantasmas', 'resucitar', 'vigilar'],
      description: 'La gran familia de la muerte. Los Hécata reúnen a los antiguos Giovanni, Samedi, Nagaraja y otras estirpes necrománticas bajo un mismo apellido y un mismo negocio: la muerte, en todas sus formas rentables. Tratan con fantasmas como quien trata con proveedores y llevan sus rencillas familiares con siglos de paciencia.',
      disciplines: ['auspex', 'fortitude', 'oblivion'],
      bane: {
        name: 'Beso doloroso',
        description: 'Su Beso no produce éxtasis, sino un dolor atroz. Los Hécata solo pueden alimentarse causando heridas y pérdida de sangre; un mortal no dispuesto que pueda escapar intentará huir, y los vampiros mordidos por ellos se arriesgan a un Frenesí de terror.',
      },
      compulsion: {
        name: 'Morbo',
        description: 'El vampiro necesita mover algo de un lado a otro de la frontera entre la vida y la muerte. Cualquier acción que no busque acabar con algo o devolverlo a la existencia sufre −2 dados.',
      },
      color: '#3f7068',
      colorDark: '#1f3d38',
      colorGlow: 'rgba(63,112,104,0.4)',
    },
    {
      id: 'lasombra',
      name: 'Lasombra',
      nickname: 'Los Manipuladores',
      verbs: ['hacer trampas', 'lograr', 'mandar', 'mover los hilos', 'perseverar'],
      description: 'Depredadores de sangre noble que consideran la oscuridad su derecho de nacimiento. Pilares del Sabbat durante siglos, muchos Lasombra han desertado en masa hacia la Camarilla, donde su ambición y su desprecio por la debilidad siguen intactos. Para ellos el fin justifica cualquier medio y el fracaso es imperdonable.',
      disciplines: ['dominate', 'oblivion', 'potence'],
      bane: {
        name: 'Imagen distorsionada',
        description: 'Su reflejo y su imagen grabada aparecen retorcidos. Las tiradas de Tecnología para interactuar por medios electrónicos tienen una dificultad de 2 + Severidad de la Prohibición, y los sistemas de detección electrónicos sufren una penalización igual a esa Severidad al intentar registrarlos.',
      },
      compulsion: {
        name: 'Crueldad',
        description: 'La próxima vez que el vampiro falle una acción, sufre −2 dados en todas sus tiradas hasta que consiga superar un nuevo intento de esa misma acción.',
      },
      color: '#4a3d70',
      colorDark: '#251e3c',
      colorGlow: 'rgba(74,61,112,0.4)',
    },
    {
      id: 'malkavian',
      name: 'Malkavian',
      nickname: 'Los Oráculos',
      verbs: ['adivinar', 'comprender', 'confundir', 'percibir', 'predecir'],
      description: 'Todo Malkavian está roto, y por esa grieta se cuela algo que los demás no ven. Su locura no es un adorno: es el precio y la fuente de una clarividencia que raya en lo profético. Unos oyen la Telaraña de Locura que une al clan, otros hablan con acertijos que solo tienen sentido semanas después.',
      disciplines: ['auspex', 'dominate', 'obfuscation'],
      bane: {
        name: 'Perspectiva fracturada',
        description: 'Cada Malkavian arrastra una aflicción mental concreta, acordada con el Narrador. Cuando sufre un Fracaso Bestial o una Compulsión, esa aflicción se impone: durante toda la escena resta su Severidad de la Prohibición a una categoría de reservas (Físicas, Sociales o Mentales).',
      },
      compulsion: {
        name: 'Delirio',
        description: 'Durante una escena, el vampiro sufre −2 dados en las tiradas que usen Destreza, Manipulación, Compostura o Astucia. A cambio, mientras dura resiste mejor el Frenesí de terror.',
      },
      color: '#8b4fae',
      colorDark: '#4a2760',
      colorGlow: 'rgba(139,79,174,0.4)',
    },
    {
      id: 'ministry',
      name: 'El Ministerio',
      nickname: 'Los Tentadores',
      verbs: ['cultivar', 'engañar', 'influir', 'negociar', 'persuadir'],
      description: 'Antes conocidos como los Seguidores de Set, los Ministros predican la liberación a través de la transgresión: encuentran la cadena que ata a una persona y la ayudan a romperla, sabiendo que quien rompe una cadena suele acabar encadenado a ellos. Se mueven entre sectas, cultos y vicios con paciencia de siglos.',
      disciplines: ['obfuscation', 'presence', 'protean'],
      bane: {
        name: 'Aborrecer la luz',
        description: 'Expuesto a una iluminación directa, natural o artificial, el Ministro sufre una penalización igual a su Severidad de la Prohibición en todas sus reservas de dados. Además, la luz solar le inflige daño agravado adicional.',
      },
      compulsion: {
        name: 'Transgresión',
        description: 'El vampiro debe inducir a alguien —o a sí mismo— a quebrantar una Convicción. Mientras tanto sufre −2 dados en toda reserva que no esté relacionada con la tentación. Termina cuando provoca al menos una Mancha.',
      },
      color: '#a8952f',
      colorDark: '#5d5116',
      colorGlow: 'rgba(168,149,47,0.4)',
    },
    {
      id: 'nosferatu',
      name: 'Nosferatu',
      nickname: 'Las Monstruosidades',
      verbs: ['acechar', 'espiar', 'investigar', 'observar', 'ocultar'],
      description: 'El Abrazo los deforma hasta hacerlos irreconocibles, y esa condena los ha convertido en los mejores espías de la noche. Viven en túneles y alcantarillas, se mueven por donde nadie mira y comercian con lo único que nunca pierde valor: la información. Ningún príncipe está tan bien informado como el Nosferatu que le sirve.',
      disciplines: ['animalism', 'obfuscation', 'potence'],
      bane: {
        name: 'Repulsividad',
        description: 'El Nosferatu es monstruoso a la vista y no puede pasar por humano: arrastra permanentemente el Defecto Repulsivo. Cualquier intento de disfrazarse o aparentar normalidad sufre una penalización igual a su Severidad de la Prohibición.',
      },
      compulsion: {
        name: 'Curiosidad malsana',
        description: 'El vampiro necesita hacerse con un secreto que aún no conoce. Toda acción que no le acerque a ese secreto sufre −2 dados.',
      },
      color: '#4f6b52',
      colorDark: '#28382a',
      colorGlow: 'rgba(79,107,82,0.4)',
    },
    {
      id: 'ravnos',
      name: 'Ravnos',
      nickname: 'Los Nómadas',
      verbs: ['eludir', 'embaucar', 'engañar', 'farolear', 'vagabundear'],
      description: 'Supervivientes de una catástrofe que casi borró al clan de la faz de la tierra. Los Ravnos no pueden echar raíces: la Sangre los castiga si duermen dos veces en el mismo sitio, así que viven en movimiento perpetuo, viajando ligeros y resolviendo los problemas con astucia, engaño y una temeridad que raya en lo suicida.',
      disciplines: ['animalism', 'obfuscation', 'presence'],
      bane: {
        name: 'Malditos',
        description: 'Si el Ravnos duerme durante el día en un mismo lugar más de una vez en siete noches, tira tantos dados como su Severidad de la Prohibición: por cada 10 que obtenga sufre 1 punto de daño agravado.',
      },
      compulsion: {
        name: 'Tentar al destino',
        description: 'El vampiro debe afrontar el problema que tenga delante por la vía más temeraria y peligrosa posible. Cualquier solución más prudente sufre −2 dados, hasta resolver el problema o volverlo imposible.',
      },
      color: '#c9922e',
      colorDark: '#755015',
      colorGlow: 'rgba(201,146,46,0.4)',
    },
    {
      id: 'salubri',
      name: 'Salubri',
      nickname: 'Los Fugitivos',
      verbs: ['ocultar', 'redimir', 'resistir', 'sobrevivir'],
      description: 'Un clan casi extinto y calumniado hasta el punto de que la mayoría de los Vástagos los cree un cuento. Los Salubri llevan un tercer ojo en la frente y una vocación de sanadores o guerreros-guardianes que los enfrenta a todo lo que la Camarilla representa. Quedan tan pocos que cada uno es una presa codiciada.',
      disciplines: ['auspex', 'dominate', 'fortitude'],
      bane: {
        name: 'Cazados',
        description: 'Su vitae resulta adictiva: cualquier vampiro que no sea Salubri y beba de ellos debe superar una tirada de Frenesí de hambre o seguir alimentándose sin control. Además, su tercer ojo llora sangre al activar Disciplinas, lo que puede desatar el Frenesí de los hambrientos que haya cerca.',
      },
      compulsion: {
        name: 'Empatía afectiva',
        description: 'El sufrimiento ajeno lo desborda. Cualquier acción que no vaya dirigida a aliviar el dolor de esa persona sufre −2 dados.',
      },
      color: '#7aa3c4',
      colorDark: '#3f5a72',
      colorGlow: 'rgba(122,163,196,0.4)',
    },
    {
      id: 'toreador',
      name: 'Toreador',
      nickname: 'Los Seductores',
      verbs: ['encantar', 'interpretar', 'obsesionar', 'seducir', 'tentar'],
      description: 'El clan de la belleza y de quienes la persiguen sin poder crearla ya. Mecenas, artistas y divas, los Toreador se rodean de todo lo exquisito porque la eternidad sin ello les resulta insoportable. Su refinamiento es auténtico y su crueldad también: pocas cosas son tan frías como un Toreador que se ha aburrido de ti.',
      disciplines: ['auspex', 'celerity', 'presence'],
      bane: {
        name: 'Fijación estética',
        description: 'La fealdad los debilita. En un entorno que no resulte hermoso a su gusto, sus reservas de Disciplinas sufren una penalización igual a su Severidad de la Prohibición.',
      },
      compulsion: {
        name: 'Obsesión',
        description: 'Algo hermoso captura por completo su atención: no puede hablar de otra cosa y cualquier acción ajena a ese objeto sufre −2 dados, hasta que desaparece de su vista o termina la escena.',
      },
      color: '#c44a74',
      colorDark: '#73223f',
      colorGlow: 'rgba(196,74,116,0.4)',
    },
    {
      id: 'tremere',
      name: 'Tremere',
      nickname: 'Los Brujos',
      verbs: ['aprender', 'estudiar', 'perfeccionar', 'realizar rituales y hechicerías', 'tramar'],
      description: 'Magos mortales que robaron la inmortalidad y pagaron por ello. Durante siglos su Pirámide fue la estructura más disciplinada de la Camarilla, hasta que la destrucción de su Casa Capitular de Viena la hizo añicos. Hoy son casas rivales de hechiceros sin un liderazgo claro, y eso los ha vuelto más peligrosos, no menos.',
      disciplines: ['auspex', 'blood-sorcery', 'dominate'],
      bane: {
        name: 'Sangre deficiente',
        description: 'Su vitae ha perdido la capacidad de esclavizar a otros Vástagos: un Tremere no puede crear Vínculos de Sangre con otros vampiros, aunque sí puede ser vinculado. Para vincular a un mortal necesita tantos tragos adicionales como su Severidad de la Prohibición.',
      },
      compulsion: {
        name: 'Perfeccionismo',
        description: 'Nada que no sea excelente le vale. Sufre −2 dados en todas sus reservas; si repite la acción la penalización baja a −1, y desaparece al segundo intento repetido. Termina con un éxito crítico en una Habilidad o al acabar la escena.',
      },
      color: '#9b3070',
      colorDark: '#551840',
      colorGlow: 'rgba(155,48,112,0.4)',
    },
    {
      id: 'tzimisce',
      name: 'Tzimisce',
      nickname: 'Los Dragones',
      verbs: ['controlar', 'modificar', 'poseer', 'tomar', 'transfigurar'],
      description: 'Señores feudales de la vieja Europa que moldean la carne como si fuera arcilla. Los Tzimisce son territoriales hasta lo patológico: necesitan poseer —una tierra, un linaje, una causa— y consideran el cuerpo, propio y ajeno, un material más sobre el que imponer su voluntad. Su cortesía es exquisita y su crueldad, artesanal.',
      disciplines: ['animalism', 'dominate', 'protean'],
      bane: {
        name: 'Confinados',
        description: 'Cada Tzimisce elige algo a lo que queda atado: un lugar, un grupo de personas o algo más abstracto. Debe pasar el día rodeado de aquello que custodia; si no lo hace, al despertar sufre daño agravado de Fuerza de Voluntad.',
      },
      compulsion: {
        name: 'Avaricia',
        description: 'El vampiro debe apoderarse de algo presente en la escena. Cualquier acción que no persiga ese fin sufre −2 dados.',
      },
      color: '#8a5a3c',
      colorDark: '#4c2f1d',
      colorGlow: 'rgba(138,90,60,0.4)',
    },
    {
      id: 'ventrue',
      name: 'Ventrue',
      nickname: 'Los Aristócratas',
      verbs: ['gobernar', 'influir', 'liderar', 'regir', 'resistir'],
      description: 'Los Reyes Mercaderes se consideran los líderes natos de la estirpe, y llevan tanto tiempo repitiéndolo que en buena medida han acabado teniendo razón: la mayoría de príncipes de la Camarilla son Ventrue. Gobiernan con dinero, tradición y una seguridad en sí mismos inquebrantable, incluso cuando se equivocan.',
      disciplines: ['dominate', 'fortitude', 'presence'],
      bane: {
        name: 'Gustos refinados',
        description: 'Solo puede alimentarse de un tipo muy concreto de mortal. Si bebe la sangre de alguien fuera de esa preferencia, debe gastar tantos puntos de Fuerza de Voluntad como su Severidad de la Prohibición o vomitará la sangre sin saciar nada de su Ansia.',
      },
      compulsion: {
        name: 'Arrogancia',
        description: 'Necesita que alguien obedezca una orden suya, y ha de conseguirlo sin recurrir a poderes sobrenaturales como Dominación. Hasta lograrlo sufre −2 dados en todas sus reservas.',
      },
      color: '#2f4f8f',
      colorDark: '#182c52',
      colorGlow: 'rgba(47,79,143,0.4)',
    },
  ],
}
