// Catalan translations overlay for VtM V5 discipline/power data
// Applied over the Spanish base data when language is set to Catalan

import type { DisciplineTranslation } from './disciplines.en'

type DisciplineId =
  | 'animalism'
  | 'auspex'
  | 'celerity'
  | 'dominate'
  | 'fortitude'
  | 'obfuscation'
  | 'oblivion'
  | 'potence'
  | 'presence'
  | 'protean'
  | 'blood-sorcery'
  | 'thin-blood-alchemy'

export const CA: Record<DisciplineId, DisciplineTranslation> = {

  // ── ANIMALISME ───────────────────────────────────────────────────────────────
  animalism: {
    name: 'Animalisme',
    description: 'Disciplina que permet al vampir connectar amb els animals i amb la Bèstia interior. Els mestres de l\'Animalisme es fan un amb les seves Bèsties i poden controlar animals, suprimir la Bèstia d\'altres vampirs i més.',
    tipo: 'Mental',
    amenaza: 'Baixa a mitjana. Tot i que parlar amb animals pot semblar excèntric, només les aplicacions més violentes de la Disciplina provoquen més que unes poques celles arquejades.',
    resonancia: 'Sang animal, preferentment salvatge.',
    powers: {
      'sense-the-beast': {
        name: 'Sentir la Bèstia',
        cost: 'Cap',
        dicePool: 'Resolució + Animalisme contra Compostura + Subterfugi',
        duration: 'Passiva',
        description: 'Detecta la naturalesa depredadora i l\'hostilitat de les criatures properes. Identifica vampirs, homes llop i altres sobrenaturals. Es pot usar activa o passivament (avisa d\'intencions agressives). Amb victòria crítica revela el tipus exacte i el nivell d\'Ànsia/Ràbia.',
      },
      'bond-famulus': {
        name: 'Vincle amb Famulus',
        cost: '3 Enardiments (un per nit)',
        dicePool: 'Carisma + Tracte amb Animals',
        duration: 'Fins a la mort',
        description: 'Crea un vincle mental permanent amb un animal, convertint-lo en familiar (famulus). Només se\'n pot tenir un. El famulus no envelleix mentre rebi Sang i pot fer-se servir sense cost amb Xiuxiueigs Salvatges i Comunió d\'Esperits.',
      },
      'feral-whispers': {
        name: 'Xiuxiueigs Salvatges',
        cost: '1 Enardiment (per espècie; cap amb el famulus)',
        dicePool: 'Manipulació + Animalisme, Carisma + Animalisme',
        duration: 'Una escena',
        description: 'Comunicació bidireccional amb animals i invocació dels mateixos. Dificultat segons la tasca (per exemple: vigilar un parc dif. 3; defensar un lloc amb la vida dif. 6). El marge en la invocació determina la quantitat d\'animals acudits.',
      },
      'unliving-hive': {
        name: 'Rusc No-Mort',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Estén tots els poders d\'Animalisme a eixams d\'insectes. Pot vincular-se com a famulus i niar dins del propi cos del vampir.',
        amalgama: 'Ofuscació 2',
      },
      'quell-the-beast': {
        name: 'Reprimir la Bèstia',
        cost: '1 Enardiment',
        dicePool: 'Carisma + Animalisme contra Resistència + Resolució',
        duration: 'Una escena (o marge +1 torns)',
        description: 'Una victòria contra un mortal el deixa apàtic, incapaç d\'actuar tret per sobreviure. Contra un vampir, evita que executi Arrabassament de Sang i no obté crítics conflictius. Una victòria crítica contra un vampir també posa fi al seu Frenesí.',
      },
      'animal-succulence': {
        name: 'Suculència Animal',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Alimentar-se d\'animals sacia 1 punt extra d\'Ànsia, i la Potència de Sang compta com 2 nivells menor per a les penalitzacions. Consumir el propi famulus sacia 4 punts (mai l\'últim) i augmenta l\'Atribut més associat a l\'animal en +2 fins a la següent alimentació.',
      },
      'subsume-the-spirit': {
        name: 'Comunió d\'Esperits',
        cost: '1 Enardiment (cap amb el famulus)',
        dicePool: 'Manipulació + Animalisme',
        duration: 'Una escena (indefinida amb crític)',
        description: 'Transfereix la consciència del vampir al cos d\'un animal, controlant-lo completament i utilitzant tots els seus sentits. El cos vampíric queda inconscient durant la possessió.',
      },
      'animal-dominion': {
        name: 'Control Animal',
        cost: '2 Enardiments',
        dicePool: 'Carisma + Animalisme',
        duration: 'Una escena (o fins a complir l\'ordre)',
        description: 'Domina ramats o grups sencers d\'animals simultàniament com si fossin una sola entitat. Amb victòria crítica el control és absolut i sense tirada addicional.',
      },
      'drawing-out-the-beast': {
        name: 'Expulsar la Bèstia',
        cost: '1 Enardiment',
        dicePool: 'Astúcia + Animalisme contra Compostura + Resolució',
        duration: 'Un Frenesí',
        description: 'En comptes de tirar Força de Voluntat per resistir un Frenesí de terror o fúria, tira contra la Compostura + Resolució de l\'objectiu. Amb victòria, l\'objectiu entra en Frenesí en lloc del vampir. Si falla, el vampir entra en Frenesí igualment. No pot transferir Frenesí de fam.',
      },
      'animal-messenger': {
        name: 'Missatger Animal',
        cost: '1 Enardiment (per nit)',
        dicePool: 'N/A',
        duration: 'Una nit (o més)',
        description: 'El famulus porta un missatge parlat d\'una frase a qui el seu amo designi, i el pronuncia amb la veu del mateix vampir. Si es desconeix el parador del destinatari, el famulus l\'ha de rastrejar (Resolució + Argot de Carrer o Supervivència, dificultat 2), amb un intent per nit. Lliurat el missatge, torna. Requereix Vincle amb Famulus.',
        amalgama: 'Auspex 1',
      },
      'messengers-command': {
        name: 'Ordre del Missatger',
        cost: 'Cap',
        dicePool: 'Com el Poder base (Compel·lir o Mesmerisme)',
        duration: 'La del Poder base',
        description: 'Permet llançar Compel·lir o Mesmerisme a través d\'una ordre transmesa pel famulus, tan bon punt aquest fa contacte visual amb l\'objectiu. La puntuació de Dominació emprada no pot superar l\'Animalisme de l\'usuari. Requereix Missatger Animal.',
        amalgama: 'Dominació 1',
      },
      'plague-of-beasts': {
        name: 'Plaga de Bèsties',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Animalisme contra Compostura + Tracte amb Animals',
        duration: 'Una nit',
        description: 'Marca un individu com a blanc de l\'atenció animal. Qualsevol bèstia o alimanya de la zona el busca per bordar-li, picotejar-lo i esgarrapar-lo, i li fa molt difícil ocupar-se de res que no sigui espantar-les. Els animals conserven prou instint per no posar en perill la seva pròpia supervivència.',
      },
      'influence-the-herd': {
        name: 'Influir al Ramat',
        cost: '1+ Enardiment',
        dicePool: 'Compostura + Animalisme',
        duration: 'Una nit',
        description: 'Guia l\'humor general dels animals d\'una àrea de la mida d\'un camp de futbol, ampliable amb Enardiments addicionals fins a una ciutat petita. No dirigeix accions concretes: porta el seu comportament des de la indiferència somnolenta fins a l\'agressió indiscriminada, i cada èxit dificulta els intents mundans de controlar-los.',
      },
      'coerce-the-bestial-temper': {
        name: 'Coaccionar el Temperament Bestial',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Animalisme',
        duration: 'Fins que acabi (mentre taral·legi)',
        description: 'Cantant o taral·lejant suaument, el vampir estira els fils de totes les Bèsties properes. Cada èxit de marge apuja o abaixa en 1 la dificultat per resistir el Frenesí de tots els vampirs que puguin sentir-lo; si l’abaixa, els que ja estiguin en Frenesí poden tirar de nou per sortir-ne.',
      },
    },
  },

  // ── AUSPEX ───────────────────────────────────────────────────────────────────
  auspex: {
    name: 'Auspex',
    description: 'Entre els majors dons i pitjors malediccions dels vampirs, Auspex permet als Vàstags discernir la veritat de la mentida, sondejar les ments dels qui els envolten i percebre la realitat a un nivell diferent al d\'altres éssers.',
    tipo: 'Mental',
    amenaza: 'Baixa. Auspex mai es manifesta de manera visible a simple vista o causa efectes que no es puguin racionalitzar.',
    resonancia: 'Flegmàtica. Artistes (especialment fotògrafs) i visionaris, certs esquizofrènics, usuaris de substàncies psicoactives, detectius.',
    powers: {
      'heightened-senses': {
        name: 'Sentits Aguditzats',
        cost: 'Cap',
        dicePool: 'Astúcia + Resolució',
        duration: 'Fins a desactivar',
        description: 'Afegeix la puntuació d\'Auspex com a daus extra a totes les proves de Percepció. Davant estímuls extrems (explosions, flaixos, olors aclaparadors) exigeix una tirada d\'Astúcia + Resolució dif. 3 o pateix −3 daus a totes les proves de percepció fins a fi d\'escena.',
      },
      'sense-the-unseen': {
        name: 'Sentir l\'Invisible',
        cost: 'Cap',
        dicePool: 'Astúcia + Auspex o Resolució + Auspex',
        duration: 'Passiva',
        description: 'Sintonitza els sentits amb presències ocultes: usuaris d\'Ofuscació, espies amb Auspex, fantasmes, rituals latents de Bruixeria de Sang. Detecció passiva del Narrador; contra una entitat que s\'oculta activament, contesa d\'Astúcia + Auspex contra la reserva rellevant de l\'objectiu.',
      },
      premonition: {
        name: 'Premonició',
        cost: '1 Enardiment (opcional)',
        dicePool: 'Resolució + Auspex',
        duration: 'Passiva',
        description: 'Rep esclats d\'intuïció, pressentiments o visions sobre perills immediats. El Narrador pot atorgar pistes passives sense que el jugador les demani.',
      },
      'shared-senses': {
        name: 'Compartir els Sentits',
        cost: '1 Enardiment',
        dicePool: 'Resolució + Auspex',
        duration: 'Una escena',
        description: 'Veu, escolta i sent a través d\'un altre mortal o vampir. Sobre desconeguts requereix línia de visió; sobre algú amb Sang de l\'usuari, a distància. La víctima el pot detectar amb Sentir l\'Invisible i expulsar-lo amb contesa Astúcia + Resolució (l\'usuari expel·lit no ho torna a intentar fins la nit següent).',
      },
      'scry-the-soul': {
        name: 'Escrutar l\'Ànima',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Auspex contra Compostura + Subterfugi',
        duration: 'Un torn',
        description: 'Llegeix l\'aura d\'una persona. El marge determina quantes preguntes respon el Narrador: estat emocional, Ressonància, si és sobrenatural, si està sota Bruixeria de Sang, si ha comès Diablerie l\'últim any. Victòria crítica revela quelcom inesperat.',
      },
      'spirits-touch': {
        name: 'Toc de l\'Esperit',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Auspex',
        duration: 'Un torn',
        description: 'En tocar un objecte o lloc, reviu les emocions i impressions deixades pels qui el van fer servir (psicometria). Com més intensa l\'emoció original, més clara la visió.',
      },
      clairvoyance: {
        name: 'Clarividència',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Auspex',
        duration: 'Uns minuts (fins a una nit vigilant)',
        description: 'Projecta els sentits a qualsevol lloc conegut o que pugui visualitzar, observant remotament sense estar-hi físicament present.',
      },
      possession: {
        name: 'Possessió',
        cost: '2 Enardiments',
        dicePool: 'Resolució + Auspex contra Resolució + Intel·ligència',
        duration: 'Fins que acabi',
        description: 'Només sobre mortals (els Ghouls han d\'estar Vinculats). Requereix contacte visual previ. El cos del vampir entra en trànsit similar a Letargia; el dany agreujat a l\'hoste el trenca. Fallada total = víctima immune a futurs intents durant la història.',
        amalgama: 'Dominació 3',
      },
      telepathy: {
        name: 'Telepatia',
        cost: '1 Enardiment (+1 Força de Voluntat)',
        dicePool: 'Resolució + Auspex contra Astúcia + Subterfugi',
        duration: '1 minut (per Enardiment; una escena si és voluntari)',
        description: 'Llegeix ments i projecta pensaments propis. Pot extreure records específics, comunicar-se sense paraules o detectar mentides directament des de la font.',
      },
      panacea: {
        name: 'Panacea',
        cost: '1 Enardiment (+1 Força de Voluntat)',
        dicePool: 'Compostura + Auspex',
        duration: 'N/A',
        description: 'Calma la inquietud mental o emocional de l\'objectiu i li retorna una mica de resolució. Restaura tant dany superficial de Força de Voluntat com el marge, o 1 nivell agreujat per cada tres èxits de marge. Un objectiu per nit: calmar-ne més fa que l\'usuari carregui amb part del pes.',
        amalgama: 'Fortalesa 1',
      },
      'reveal-temperament': {
        name: 'Revelar Temperament',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Auspex contra Compostura + Subterfugi',
        duration: 'Una escena',
        description: 'Permet olorar la Ressonància d\'un objectiu i qualsevol Discràsia que allotgi la seva sang. També revela si un altre vampir s\'ha alimentat fa poc i la Ressonància, si n\'hi ha, de la seva darrera víctima.',
      },
      'fatal-flaw': {
        name: 'Defecte Fatal',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Auspex contra Compostura o Resistència + Subterfugi',
        duration: 'Una escena',
        description: 'Tot es trenca, i qui usa aquest Poder en veu els senyals abans que passi. Observant el treball subtil de l\'entropia, el vampir dedueix el taló d\'Aquil·les de l\'objectiu: una escletxa en la seva façana mental o una debilitat en la seva armadura.',
        amalgama: 'Oblit 1',
      },
      'unburdening-the-bestial-soul': {
        name: 'Alleujament de l\'Ànima Bestial',
        cost: '2 Enardiments (i 1 Màcula)',
        dicePool: 'Compostura + Auspex contra Humanitat',
        duration: 'Una sessió',
        description: 'Comparteix part de la serenor moral de l\'usuari amb un Vàstag penedit: li retorna cert remordiment i manté a ratlla la seva Bèstia, a costa de sotmetre la seva voluntat a la de l\'usuari. Aquest Poder, vist sobretot entre els Salubri, alimenta la seva fama de lladres d\'ànimes. Requereix Panacea.',
        amalgama: 'Dominació 3',
      },
    },
  },

  // ── CELERITAT ────────────────────────────────────────────────────────────────
  celerity: {
    name: 'Celeritat',
    description: 'La Celeritat permet als vampirs moure\'s més ràpid que qualsevol criatura natural. Fa més que atorgar velocitat sobrenatural: els vampirs que la fan servir realment semblen pensar gairebé tan ràpid com actuen.',
    tipo: 'Físic',
    amenaza: 'Mitjana-alta. La majoria dels Poders de Celeritat són clarament inhumans i l\'única cosa que la salva és que són molt difícils de captar en una pel·lícula o fotografia.',
    resonancia: 'Colèrica. Por i terror absolut, corredors, atletes, usuaris d\'alcaloides i amfetamines, jugadors habituals de shooters en primera persona i altres jocs d\'acció ràpida.',
    powers: {
      'cats-grace': {
        name: 'Gràcia Felina',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Equilibri i elegància sobrehumans. Mai ensopega ni cau involuntàriament; pot moure\'s per superfícies inestables, estretes o relliscoses sense dificultat.',
      },
      'rapid-reflexes': {
        name: 'Reflexos Ràpids',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'No pateix penalització a les reserves de defensa per manca de cobertura contra atacs d\'Armes de Foc. A més, pot fer una acció menor (fins a 2 daus) per torn sense cost, com preparar o recarregar.',
      },
      fleetness: {
        name: 'Rapidesa',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Afegeix el valor de Celeritat com a daus extra a les reserves de Destresa que no siguin de combat. Un cop per torn, pot fer servir Destresa + Atletisme per defensar-se.',
      },
      blink: {
        name: 'Parpelleig',
        cost: '1 Enardiment',
        dicePool: 'Destresa + Atletisme o el que sigui necessari',
        duration: 'Un torn',
        description: 'Es desplaça en línia recta a velocitat invisible, reposicionant-se en combat o escapant abans que ningú pugui reaccionar. Els testimonis només veuen el punt d\'inici i el d\'arribada.',
      },
      traversal: {
        name: 'Recorregut',
        cost: '1 Enardiment',
        dicePool: 'Destresa + Atletisme',
        duration: 'Un torn',
        description: 'Corre per parets, sostres i fins i tot aigua si té embranzida. Dificultat entre 3 (superfície inclinada amb tracció) i 6 (vertical relliscosa o aigua). El marge determina la distància assolida; aigua més de 60 m o 30 pisos sol excedir l\'abast.',
      },
      'unerring-aim': {
        name: 'Punteria Certera',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Un atac',
        description: 'El temps s\'alenteix perceptiblement, permetent trets o llançaments de precisió impossible fins i tot contra objectius en moviment.',
        amalgama: 'Auspex 2',
      },
      'draught-of-elegance': {
        name: 'Glop d\'Elegància',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una nit (vampirs: fins a alimentar-se)',
        description: 'La Sang es satura amb Celeritat. Beure un Enardiment de l\'usuari atorga al bevedor Celeritat temporal igual a la meitat (arrodonit avall) del donant, amb accés als mateixos Poders (sense Amalgames) fins a aquest nivell.',
      },
      'lightning-strike': {
        name: 'Cop Llampec',
        cost: '1 Enardiment',
        dicePool: 'Reserva de combat normal (Destresa + Atletisme o Baralla)',
        duration: 'Un atac',
        description: 'Colpeja a velocitat invisible abans que l\'objectiu pugui reaccionar; l\'atac va a dificultat 1. Un oponent amb Celeritat 5 pot anular el Poder gastant el seu propi Enardiment i defensant-se a la mateixa velocitat.',
      },
      'split-second': {
        name: 'Segon Trencat',
        cost: '1 Enardiment',
        dicePool: 'Reserva d\'acció normal (segons l\'activitat)',
        duration: 'Una acció',
        description: 'Pot actuar al mateix instant en què és atacat, interrompent l\'acció de l\'atacant abans que es completi. Pot usar aquesta acció per atacar, escapar o qualsevol acció ràpida.',
      },
      urgency: {
        name: 'Urgència',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir despatxa a velocitat encegadora tasques que portarien torns: escriu, repara o construeix en temps rècord, tractant accions completes com a accions secundàries. La concentració que exigeix li impedeix emprar aquesta velocitat de manera ofensiva.',
      },
      zigzag: {
        name: 'Ziga-zaga',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir percep com a lents els projectils —ganivets llançats o bales— i els esquiva a voluntat. No perd daus en defensar-se de diversos atacs a distància amb Destresa + Atletisme i suma la seva puntuació de Celeritat a aquestes tirades. Requereix Reflexos Ràpids.',
      },
      'unseen-strike': {
        name: 'Atac Invisible',
        cost: '2 Enardiments',
        dicePool: 'Destresa + Celeritat contra Astúcia + Consciència',
        duration: 'Un torn',
        description: 'El vampir desapareix a plena vista, es planta a l\'instant vora un enemic i li assesta un atac fatal. Qui domina aquest art pot girar la truita davant els seus perseguidors i escapar no només amb la seva vida, sinó també amb la de la seva presa. Requereix Pestanyeig.',
        amalgama: 'Ofuscació 4',
      },
      'blurred-momentum': {
        name: 'Ímpetu Borrós',
        cost: '1 Enardiment (per torn)',
        dicePool: 'N/A',
        duration: 'Fins que acabi',
        description: 'El moviment del vampir es converteix en un borrall vibrant. Els atacs que aconsegueixin menys èxits que la seva puntuació de Celeritat fallen sempre, fins i tot els atacs per sorpresa i els que no permeten tirada de defensa.',
      },
    },
  },

  // ── DOMINACIÓ ────────────────────────────────────────────────────────────────
  dominate: {
    name: 'Dominació',
    description: 'La Dominació permet al vampir controlar les accions dels altres, manipular els seus records i obligar les criatures vives a fer actes que no farien per pròpia voluntat. La majoria dels Poders requereixen contacte visual amb la víctima.',
    tipo: 'Mental',
    amenaza: 'Baixa. Excepte que algú Domini tot un auditori perquè salti pels penya-segats de Dover, segueix sent un dels Poders vampírics més subtils.',
    resonancia: 'Flegmàtica. La sang dels submisos o dels dominants, amos i esclaus, capitans de la indústria, els poderosos, líders de sectes i els seus seguidors.',
    powers: {
      compel: {
        name: 'Compel·lir',
        cost: 'Cap',
        dicePool: 'Carisma + Dominació contra Intel·ligència + Resolució',
        duration: 'Una escena',
        description: 'Imposa una ordre simple i irresistible mitjançant contacte visual: una frase, una sola acció. La víctima l\'executa immediatament fins i tot si va contra els seus interessos.',
      },
      'cloud-memory': {
        name: 'Enterbolir la Memòria',
        cost: 'Cap',
        dicePool: 'Carisma + Dominació contra Astúcia + Resolució',
        duration: 'Indefinida',
        description: 'Amb la paraula «oblida!», fa que la víctima oblidi el moment actual i els últims minuts (suficient per emmascarar una alimentació superficial o trobada casual). Sense tirada contra mortal desprevingut. Si és pressionada, la víctima nota que li falten minuts.',
      },
      dementation: {
        name: 'Dementació',
        cost: '1 Enardiment (per escena)',
        dicePool: 'Manipulació + Dominació contra Compostura + Intel·ligència',
        duration: 'Una escena',
        description: 'A través de conversa casual, un atac per torn causa dany superficial a la Força de Voluntat. Un mortal Impedit pateix un atac de nervis o brot psicòtic. Un vampir afectat sucumbeix a una Compulsió escollida per l\'usuari.',
        amalgama: 'Ofuscació 2',
      },
      mesmerize: {
        name: 'Mesmerisme',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Dominació contra Intel·ligència + Resolució',
        duration: 'Una escena (o fins a complir l\'ordre)',
        description: 'Hipnotitza la víctima implantant ordres complexes que executarà com si fossin pròpies. Requereix contacte visual prolongat i relatiu silenci.',
      },
      'submerged-directive': {
        name: 'Directriu Submergida',
        cost: 'Cap',
        dicePool: 'Com Mesmerisme',
        duration: 'Passiva (no expira)',
        description: 'Amplia Mesmerisme per implantar ordres amb disparadors condicionals: l\'ordre roman adormida fins que ocorri un esdeveniment específic fixat pel vampir.',
      },
      'forgetful-mind': {
        name: 'Ment Oblidadissa',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Dominació contra Intel·ligència + Resolució',
        duration: 'Indefinida',
        description: 'Reescriu o esborra fragments sencers de memòria. Cada punt de marge permet afegir o eliminar un record. La víctima els recorda vagos i borrosos, susceptibles d\'esfondrar-se sota interrogatori. Victòria crítica crea records perfectes i indistinguibles.',
      },
      rationalize: {
        name: 'Racionalitzar',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Indefinida',
        description: 'Les víctimes defensen com a pròpia qualsevol acció feta sota Dominació. Si són pressionades, poden tirar Astúcia + Consciència dif. 5 per qüestionar la pròpia declaració (i possiblement la cordura). L\'exposició prolongada causa trauma mental greu.',
      },
      'terminal-decree': {
        name: 'Decret Terminal',
        cost: 'Cap (cost en Humanitat)',
        dicePool: 'Com el Poder base (el de Dominació usat)',
        duration: 'Passiva',
        description: 'Elimina el fallada automàtica de les ordres que causen mort o lesió greu; ara es resisteixen amb tirada normal (segons el Poder aplicat). Pot fer que mortals se suïcidin o que vampirs caminin al foc. Cost sever en Humanitat.',
      },
      'mass-manipulation': {
        name: 'Manipulació en Massa',
        cost: '+1 Enardiment (sobre el Poder base)',
        dicePool: 'Com el Poder base, contra l\'oponent més fort del grup',
        duration: 'La del Poder base',
        description: 'Amplifica qualsevol altre Poder de Dominació per afectar grups de mortals o vampirs. Totes les víctimes han de veure els ulls de l\'usuari. La tirada es fa contra l\'oponent més fort del grup.',
      },
      'slavish-devotion': {
        name: 'Devoció Servil',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Les ments dels qui ja són sota la Dominació del vampir es reforcen contra les interferències alienes: qualsevol intent d\'un altre Vàstag de Dominar-los pateix una penalització de daus igual a la Fortalesa de l\'usuari.',
        amalgama: 'Fortalesa 1',
      },
      'domitors-favor': {
        name: 'Favor del Domitor',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Un mes',
        description: 'Un esclau amb Vincle de Sang amb el vampir troba molt més difícil actuar contra el seu amo: les seves tirades de resistència pateixen una penalització de 3 daus i no hi pot gastar Força de Voluntat. Els Tzimisce que usen Dominació l\'aprecien especialment.',
      },
      'ancestral-dominion': {
        name: 'Control Ancestral',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Dominació contra Intel·ligència + Ocultisme',
        duration: 'Una escena (o fins a complir l\'ordre)',
        description: 'Permet imposar la voluntat a un descendent a través de la Sang, sense contacte visual ni cap paraula, encara que l\'objectiu normalment fes el contrari. Els vampirs saben instintivament quan un avantpassat els està manipulant així. Requereix Mesmerisme.',
        amalgama: 'Bruixeria de Sang 2',
      },
      'implant-suggestion': {
        name: 'Implantar Suggestió',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Dominació contra Compostura + Resolució',
        duration: 'Una escena',
        description: 'Altera temporalment la personalitat o les opinions del subjecte: pot fer que desitgi un desconegut, abandoni la seva família, desconfiï de les seves pròpies creences o simplement vulgui una cervesa. Usar-lo sense discreció sol costar l\'ostracisme entre els Vàstags.',
        amalgama: 'Presència 1',
      },
    },
  },

  // ── FORTALESA ────────────────────────────────────────────────────────────────
  fortitude: {
    name: 'Fortalesa',
    description: 'Molt apreciada pels immortals, la Fortalesa permet resistir assalts físics i mentals. Els qui posseeixen Fortalesa són exemples dels pilars impassibles de la societat dels Vàstags, capaços de resistir cops i encantaments sense moure\'s o mostrar deteriorament.',
    tipo: 'Físic',
    amenaza: 'Mitjana. Els testimonis sens dubte reaccionen quan algú rep una pallissa brutal o una pluja de bales i en surt aparentment il·lès.',
    resonancia: 'Melancòlica. Supervivents de guerra, maltractaments o desgràcies; corredors de resistència; alpinistes; infanteria i forces especials; aquells amb un sistema immunològic molt fort.',
    powers: {
      'unswayable-mind': {
        name: 'Ment Impertorbable',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Resistència mística a la manipulació mental mundana: coacció, drogues, tortura, interrogatori. Afegeix Fortalesa a totes les tirades de resistència contra aquests efectes.',
      },
      resilience: {
        name: 'Resiliència',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Afegeix el valor de Fortalesa directament com a caselles extra de Salut. Passiu i permanent; augmenta la resistència total del vampir de forma immediata.',
      },
      'enduring-beasts': {
        name: 'Bèsties Resistents',
        cost: '1 Enardiment (cap amb el famulus)',
        dicePool: 'Resistència + Animalisme (per a animals que no siguin famulus)',
        duration: 'Una escena',
        description: 'Comparteix part de la duresa sobrenatural del vampir amb els animals sota el seu control, augmentant la seva resistència al dany.',
        amalgama: 'Animalisme 1',
      },
      toughness: {
        name: 'Duresa',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Converteix una quantitat de dany agreujat igual a la puntuació de Fortalesa en superficial quan el pateix. Aquest superficial no es cura durant l\'escena. Converteix per escena (no per ferida). Es pot activar de forma reflexa en rebre agreujat amb Astúcia + Supervivència dif. 3.',
      },
      'defy-bane': {
        name: 'Desafiar la Prohibició',
        cost: '1 Enardiment',
        dicePool: 'Astúcia + Supervivència (per activar-lo en mode reflex)',
        duration: 'Una escena',
        description: 'Resistència temporal al foc, la llum solar i altres ferides que amenacin amb la Mort Definitiva. Es pot activar de forma reflexa en rebre agreujat amb Astúcia + Supervivència dif. 3.',
      },
      'fortify-the-inner-facade': {
        name: 'Fortificar la Façana Interior',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Protegeix la ment contra Dominació, Auspex i altres poders mentals. Afegeix Fortalesa a les tirades de resistència contra poders que afectin la ment.',
      },
      'draught-of-endurance': {
        name: 'Glop d\'Aguant',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una nit (vampirs: fins a alimentar-se)',
        description: 'La Sang es satura amb Fortalesa. Beure un Enardiment de l\'usuari atorga al bevedor Fortalesa temporal igual a la meitat (arrodonit avall) del donant, amb accés als mateixos Poders (sense Amalgames) fins a aquest nivell.',
      },
      'prowess-from-pain': {
        name: 'Coratge pel Dolor',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir ja no pateix penalitzacions per dany a la Salut durant el torn, incloent-hi el foc (però no la llum solar). Una victòria crítica en una tirada d\'atac supera aquest Poder.',
      },
      'flesh-of-marble': {
        name: 'Carn de Marbre',
        cost: '2 Enardiments',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir ignora la primera font de dany físic cada torn, incloent-hi el foc (però no la llum solar). Si hi ha confusió sobre quina és la «primera», el vampir ignora la font que més dany causi aquell torn. Una victòria crítica en un atac supera aquest Poder.',
      },
      'earths-perseverance': {
        name: 'Perseverança de la Terra',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir recorre a la permanència de la Terra, s’afermat al terra i esdevé gairebé impossible de moure: només es desplaça si ell decideix fer-ho. No el fa resistent al dany, i encara pot ser aixafat o fet miques igual que el terra que trepitja.',
      },
      'invigorating-vitae': {
        name: 'Vitae Vigoritzant',
        cost: 'Cap (a banda de donar Sang)',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'La Sang del vampir repara la carn mortal i cura mals amb una eficàcia sorprenent: els éssers vius que prenguin la seva Vitae recuperen la salut a gran velocitat.',
        amalgama: 'Auspex 1',
      },
      valeren: {
        name: 'Valeren',
        cost: '1 Enardiment (i Salut segons el cas)',
        dicePool: 'Intel·ligència + Fortalesa',
        duration: 'N/A',
        description: 'El vampir projecta la seva Fortalesa cap enfora i disposa el poder de la seva Sang per sanar el cos ferit d’un altre vampir.',
        amalgama: 'Auspex 1',
      },
      'gorgons-scales': {
        name: 'Escates de Gòrgona',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena (o fins a perdre la Ressonància)',
        description: 'La Ressonància de la darrera sang presa concedeix una defensa diferent: Colèrica consumeix l\'estaca clavada al cor, Flemàtica dóna +4 daus contra els Poders d\'Auspex que revelarien res del vampir, i Melancòlica i Sanguínia redueixen a superficial el dany agreujat del foc i de la llum solar. La Ressonància es perd en usar-la.',
      },
    },
  },

  // ── OFUSCACIÓ ────────────────────────────────────────────────────────────────
  obfuscation: {
    name: 'Ofuscació',
    description: 'Per als Vàstags que practiquen Ofuscació, la Disciplina proporciona la cobertura perfecta per acostar-se a una víctima, semblar inofensius i escapar quan els ànims es caldegen massa. Els Poders d\'Ofuscació funcionen mitjançant mesmerisme ambiental de baix nivell.',
    tipo: 'Mental',
    amenaza: 'Baixa. Evitar la detecció és l\'objectiu d\'aquesta Disciplina.',
    resonancia: 'Melancòlica. Els ignorats i invisibles, els sense sostre, oblidats i deprimits; espies, carteristes, servents excel·lents, encarregats de material i tramoistes.',
    clanes: ['Banu Haqim', 'El Ministeri', 'Malkavian', 'Nosferatu', 'Ravnos'],
    powers: {
      'cloak-of-shadows': {
        name: 'Capa d\'Ombres',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Si està quiet i amb alguna cobertura, el vampir es fon amb l\'entorn. Pràcticament invisible per a qui no sàpiga exactament on mirar.',
      },
      'silence-of-death': {
        name: 'Silenci de la Mort',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Silencia passos, roba, col·lisions menors i altres sons personals. Només Sentir l\'Invisible (Auspex 1) pot detectar l\'usuari. No anul·la sons que faci fora del seu espai personal (llançar objectes, cop de porta).',
      },
      'unseen-passage': {
        name: 'Pas Invisible',
        cost: '1 Enardiment',
        dicePool: 'Astúcia + Sigil (per mantenir-se ocult en moviment)',
        duration: 'Una escena (o fins a ser detectat)',
        description: 'Es mou mentre roman ocult. Funciona automàticament si no emet olors aclaparadors ni sons més forts que un xiuxiueig. Només si atrau l\'atenció, l\'observador pot tirar per detectar-lo. No pot usar-se per desaparèixer mentre és observat (falla automàticament).',
      },
      'ghost-in-the-machine': {
        name: 'Fantasma en la Màquina',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'La del Poder base',
        description: 'En directe, se\'l tracta com si estiguessin davant del vampir. En gravacions i fotografies, +3 a la dificultat per identificar-lo (imatge borrosa). +3 daus a les reserves per eludir vigilància electrònica i contramesures automatitzades.',
      },
      'mask-of-a-thousand-faces': {
        name: 'Màscara de les Mil Cares',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Subterfugi (per passar desapercebut activament)',
        duration: 'Una escena',
        description: 'Sense tirada. Adopta l\'aparença d\'un desconegut oblidable del mateix sexe i complexió similar; la roba s\'adapta a l\'entorn (vigilant en una oficina, operari en una fàbrica). No proporciona identificació ni enganya en un control d\'identitat. Sentir l\'Invisible el detecta.',
      },
      vanish: {
        name: 'Esvair-se',
        cost: 'El del Poder base',
        dicePool: 'Astúcia + Ofuscació contra Astúcia + Consciència',
        duration: 'La del Poder base',
        description: '(Prerequisit: Capa d\'Ombres) Desapareix fins i tot sota observació directa. Amb victòria, l\'observador dubta que el vampir hi fos. Amb victòria crítica, el vampir desapareix per complet dels seus records. No afecta la memòria d\'altres vampirs. Un cop per escena.',
      },
      conceal: {
        name: 'Ocultar',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Ofuscació',
        duration: 'Una nit (+1 per marge)',
        description: 'Oculta un objecte inanimat tocant-lo. Dificultat entre 2 (anell entre records) i 6 (casa en una plaça oberta). Mida màxima: casa de dos pisos. Oculta també el seu contingut si l\'observador no hi entra. Una nit +1 per punt de marge.',
        amalgama: 'Auspex 3',
      },
      'impostors-guise': {
        name: 'Disfressa de l\'Impostor',
        cost: '1 Enardiment',
        dicePool: 'Astúcia + Ofuscació, Manipulació + Interpretació',
        duration: 'Una escena',
        description: '(Prerequisit: Màscara de les Mil Cares) Adopta l\'aparença exacta d\'una persona específica coneguda, incloent-hi la veu i els manerismes.',
      },
      'cloak-the-gathering': {
        name: 'Encobriment de la Concurrència',
        cost: '+1 Enardiment (sobre el Poder base)',
        dicePool: 'N/A',
        duration: 'La del Poder base',
        description: 'Estén qualsevol Poder d\'Ofuscació a un grup proper sense tirada. Els membres poden veure\'s entre ells. Si algú del grup (que no sigui l\'usuari) queda descobert, la resta segueix oculta. Si és l\'usuari qui és descobert, tots queden exposats.',
      },
      chimerstry: {
        name: 'Quimerisme',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Ofuscació contra Compostura + Astúcia',
        duration: 'Un torn',
        description: 'Crea al·lucinacions breus però vívides que afecten un sol sentit: un cop d\'ull de reüll, una veu tot just sentida, un frec. Duren just el necessari per causar impressió, així que no serveixen per a res que aguanti un examen, com un carnet fals.',
        amalgama: 'Presència 1',
      },
      'fata-morgana': {
        name: 'Fata Morgana',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Ofuscació',
        duration: 'Una escena',
        description: 'Al·lucinacions elaborades que qualsevol capaç de veure l\'usuari —o a qui ell vegi— experimenta amb diversos sentits alhora. No alteren la realitat ni causen dany, no poden amagar objectes ni bloquejar la vista, no sobrecarreguen els sentits i no queden registrades per càmeres.',
        amalgama: 'Presència 2',
      },
      'mental-maze': {
        name: 'Laberint Mental',
        cost: '1 Enardiment (o 3)',
        dicePool: 'Carisma + Ofuscació contra Astúcia + Resolució',
        duration: 'Una nit',
        description: 'Elimina tot sentit de l\'orientació de la víctima i l\'empresona al lloc on es troba. L\'indret sembla replegar-se sobre si mateix, cada sortida sembla portar-la més endins del laberint i al final la trenca pel pànic.',
        amalgama: 'Dominació 1',
      },
      'mental-masquerade': {
        name: 'Mascarada Mental',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Ofuscació',
        duration: 'Una escena',
        description: 'Presenta una personalitat completament diferent a qui llegeixi el seu estat mental, la seva aura o els seus pensaments per mitjans sobrenaturals. Qui li miri la ment només veu el que l\'usuari vol que vegi, i només els endevins més dotats travessen la façana.',
        amalgama: 'Dominació 2',
      },
    },
  },

  // ── POTÈNCIA ─────────────────────────────────────────────────────────────────
  // ── OBLIVION ─────────────────────────────────────────────────────────────────
  oblivion: {
    name: 'Oblit',
    description: 'Pocs Vàstags fora dels Clans Lasombra i Hécata coneixen l\'Oblit, i per a la Camarilla això és bo. Els seus Poders controlen les ombres i els esperits d\'un pla de mort i buit que uns anomenen l\'Abisme i d\'altres el Laberint: embolcallar-se en la nit, esclavitzar espectres o estrangular una víctima amb la seva pròpia ombra. Les ombres abissals no es poden atacar per mitjans físics, però pateixen dany del foc i de la llum solar, i la Disciplina no funciona en zones molt il·luminades. Nota: un 1 o un 10 en una comprovació d\'Enardiment d\'Oblit causa una Màcula.',
    tipo: 'Mental',
    amenaza: 'Mitjana-alta. Les ombres abissals poques vegades es mostren bé en càmera, però són òbviament antinaturals si es veuen en persona.',
    resonancia: 'Sociòpates i gent emocionalment distant. Sang lliure de Ressonància.',
    powers: {
      'ashes-to-ashes': {
        name: 'Cendres a les Cendres',
        cost: '1 Enardiment',
        dicePool: 'Resistència + Oblit contra Resistència + Medicina o Fortalesa',
        duration: 'Variable',
        description: 'Introduint Vitae en un cadàver, el vampir el desintegra en tres torns. No funciona sobre vampirs; contra un cadàver animat exigeix una contesa, i un fracàs total el deixa podrit però immune a aquest Poder per sempre, de qualsevol usuari.',
      },
      'binding-fetter': {
        name: 'El Grilló Vinculant',
        cost: 'Cap',
        dicePool: 'Astúcia + Oblit',
        duration: 'Una escena',
        description: 'Identifica els Grillons: objectes, edificis o fins i tot persones que lliguen un fantasma a l\'existència. Les seves aures es perceben per la vista, l\'olfacte i altres sentits, però la concentració distreu de tota la resta i imposa −2 a les tirades de Consciència, Astúcia i Resolució.',
      },
      'shadow-cloak': {
        name: 'Mantell d\'Ombres',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Aplicant subtilment la influència de l\'Oblit a les ombres ambientals, el vampir emmascara la seva aparença o sembla més sinistre i amenaçador: +2 daus a les tirades de Sigil i a les d\'Intimidació contra mortals.',
      },
      'oblivions-sight': {
        name: 'Vista de l\'Oblit',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Els ulls del vampir es tornen negres. Ignora totes les penalitzacions per manca de llum, incloses les d\'origen sobrenatural, i percep els fantasmes que no amaguin activament la seva presència, que se li apareixen com vulguin.',
      },
      'shadow-cast': {
        name: 'Projectar Ombres',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Conjura una ombra sobrenatural del propi cos, independent de la llum ambiental, amb la qual manifestar la resta de Poders de l\'Oblit. Pot dirigir-la i allargar-la fins al doble de la seva puntuació d\'Oblit en metres, i només l\'esborra la llum solar directa.',
      },
      'arms-of-ahriman': {
        name: 'Braços d\'Ahrimán',
        cost: '1 Enardiment',
        dicePool: 'Astúcia + Oblit',
        duration: 'Una escena',
        description: 'Tentacles d\'ombra broten dels punts foscos de l\'entorn i convergeixen sobre una o més víctimes per apallissar-les o fer-los presa a distància. Ataquen amb Astúcia + Oblit i sumen la meitat de la Potència de l\'usuari al dany, però aquest no pot fer res més mentre els controla.',
        amalgama: 'Potència 2',
      },
      'where-the-veil-thins': {
        name: 'On el Vel s\'Aprima',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Oblit',
        duration: 'Un torn',
        description: 'Determina la densitat del Mantell entre el món dels vius i el dels morts en una àrea de fins a un edifici o monument sencer. On és més prim, la salut dels mortals se\'n ressent i les tirades d\'Oblit resulten més fàcils; sense aquest Poder no es pot aprofitar aquest aprimament.',
      },
      'fatal-precognition': {
        name: 'Predicció Fatal',
        cost: '1 Enardiment',
        dicePool: 'Resolució + Oblit contra Astúcia + Ocultisme',
        duration: '24 hores',
        description: 'Ordeix fils invisibles d\'entropia en un objectiu mortal i augmenta les probabilitats que pateixi dany o fins i tot la mort en el termini d\'una nit i un dia. Recorda una maledicció, però el vampir no pot interferir amb el condemnat sense trencar l\'efecte.',
        amalgama: 'Auspex 2',
      },
      'aura-of-decay': {
        name: 'Aura de Descomposició',
        cost: '1 Enardiment',
        dicePool: 'Resistència + Oblit contra Resistència + Medicina o Fortalesa',
        duration: 'Una escena',
        description: 'Les plantes es marceixen, el menjar es fa malbé i els animals i les persones emmalalteixen al voltant del vampir, que contamina la vitalitat amb podridura i accelera l\'erosió de la vida.',
      },
      'passion-feast': {
        name: 'Festí de Passió',
        cost: 'Cap',
        dicePool: 'Resolució + Oblit contra Resolució + Compostura',
        duration: 'Passiva',
        description: 'Permet subsistir de les Passions dels wraiths en lloc de sang, cosa que sosté el vampir durant llargues estades a les terres dels morts a costa de turmentar l\'esperit del qual s\'alimenta.',
        amalgama: 'Fortalesa 2',
      },
      'shadow-perspective': {
        name: 'Perspectiva d\'Ombra',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Projecta els sentits en qualsevol ombra a la vista —inclosa la pròpia, si usa Projectar Ombres— i veu i sent des de qualsevol part d\'ella. La seva presència allà és indetectable llevat de per mitjans sobrenaturals.',
      },
      'shadow-servant': {
        name: 'Servent Ombrívol',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir atorga vida independent a una part de la seva ombra i l\'envia a espiar o a inquietar els seus enemics.',
        amalgama: 'Auspex 1',
      },
      'touch-of-oblivion': {
        name: 'Toc de l\'Oblit',
        cost: '1 Enardiment',
        dicePool: 'Força + Baralla (si la víctima es resisteix)',
        duration: 'Un torn',
        description: 'Un simple toc envelleix de manera catastròfica la part afectada: marceix un membre, ofega una gola o encega un parell d\'ulls. Infligeix 2 nivells de dany agreujat i una ferida incapacitant.',
      },
      'stygian-shroud': {
        name: 'Mantell Estigi',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Estén una capa de foscor sobre una àrea circular igual al doble de la seva puntuació d\'Oblit en metres, que esmorteeix els sons i els torna indistints. Des de fora només es veu una ombra expandint-se sobre cada superfície, inclosos els cossos de les víctimes.',
      },
      'necrotic-plague': {
        name: 'Plaga Necròtica',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Oblit contra Resistència + Resistència o Fortalesa',
        duration: 'Variable',
        description: 'Amb un simple contacte, el vampir enverina la sang de la víctima amb una malaltia que arruïna i assola el seu cos. També pot fer-la contagiosa, per transmetre el mateix dany a altres mortals.',
      },
      'tenebrous-avatar': {
        name: 'Avatar Tenebrós',
        cost: '2 Enardiments',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir converteix la seva pròpia substància en ombra i s\'escola per qualsevol superfície i per les escletxes més minúscules. Mentre sigui en aquesta forma, només poden fer-li mal el foc i la llum solar.',
      },
      'shadow-step': {
        name: 'Caminar per les Ombres',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Un torn',
        description: 'Endinsant-se en una ombra prou gran per abastar-lo, el vampir desapareix i surt un torn més tard d\'una altra ombra llunyana que pugui veure, sigui a simple vista o per mitjans místics. El dany espiritual amb què de vegades emergeix suggereix que travessa alguna cosa nauseabunda.',
      },
      'skuld-fulfilled': {
        name: 'Skuld Complert',
        cost: '2 Enardiments',
        dicePool: 'Resistència + Oblit contra Resistència + Resistència o Fortalesa',
        duration: 'Variable',
        description: 'Reinfecta una víctima amb malalties de les quals s\'havia recuperat, trenca ossos guarits fa molt i revoca la immunitat a l\'envelliment dels Ghouls. No funciona sobre vampirs, però és una manera eficaç de saltar-se\'ls colpejant els seus servents.',
      },
    },
  },

  potence: {
    name: 'Potència',
    description: 'La Potència és la força impulsada amb Vitae més enllà de les capacitats d\'altres vampirs. És la capacitat del vampir d\'obligar el seu cos a fer accions impossibles de replicar pels mortals.',
    tipo: 'Físic',
    amenaza: 'De mitjana a alta. Els usos menors de la Disciplina podrien passar com a "força histèrica", però quan el paviment es clivella i els edificis comencen a esfondrar-se, aquesta explicació perd credibilitat.',
    resonancia: 'Colèrica. Els forts i saludables; atletes i homes i dones joves en el seu millor moment, rates de gimnàs, lluitadors, treballadors de la construcció i llenyataires, estibadors.',
    powers: {
      'lethal-body': {
        name: 'Cos Letal',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Els atacs sense armes poden causar dany agreujat a la Salut a mortals, a elecció de l\'usuari. Ignoren un nivell d\'armadura per nivell de Potència.',
      },
      'soaring-leap': {
        name: 'Salt Vertiginós',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Salta en vertical tants metres com 3× el seu nivell de Potència, i en horitzontal 5× el seu nivell de Potència. Sense necessitat d\'embranzida.',
      },
      prowess: {
        name: 'Bravura',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Afegeix el nivell de Potència al dany sense armes i a les proeses de Força. Afegeix la meitat de Potència (arrodonit amunt) al dany de Baralla amb Armes.',
      },
      'uncanny-grip': {
        name: 'Grapa Sorprenent',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Èxit automàtic en qualsevol prova per escalar superfícies no metàl·liques. Deixa marques o deformacions visibles (Intel·ligència + Investigació dif. 2 per veure-les). Pot penjar-se d\'una paret o sostre durant una escena. Les superfícies fines de vidre poden esberlar-se.',
      },
      'brutal-feed': {
        name: 'Alimentació Brutal',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Una alimentació',
        description: 'Drena completament un humà en segons (normalment un torn). Cada punt d\'Ànsia saciat causa un punt de dany agreujat a la Salut de la víctima. En vampirs, només superficial. En combat s\'utilitza després d\'un atac de Baralla amb èxit amb els ullals. L\'armadura no protegeix.',
      },
      'spark-of-rage': {
        name: 'Espurna d\'Ira',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Potència',
        duration: 'Una escena',
        description: 'Transmet ràbia sobrenatural a criatures properes, podent desencadenar Frenesís en altres vampirs o brutalitat en mortals.',
        amalgama: 'Presència 3',
      },
      'draught-of-might': {
        name: 'Glop de Poder',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una nit (vampirs: fins a alimentar-se)',
        description: 'La Sang es satura amb Potència. Beure un Enardiment de l\'usuari atorga al bevedor Potència temporal igual a la meitat (arrodonit avall) del donant, amb accés als mateixos Poders (sense Amalgames) fins a aquest nivell.',
      },
      'fist-of-caine': {
        name: 'Puny de Caín',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Durant una escena, els atacs de Baralla causen dany agreujat a la Salut tant a mortals com a sobrenaturals. Literalment esquinça la carn i arrenca extremitats amb les mans nues.',
      },
      'earthshock': {
        name: 'Tremolor de Terra',
        cost: '2 Enardiments',
        dicePool: 'Força + Atletisme contra Destresa + Atletisme de cada objectiu',
        duration: 'Un ús',
        description: 'Colpeja el terra generant una ona de xoc que tomba i atordeix tots els oponents en un radi proper. Els afectats cauen a terra i perden la seva propera acció.',
      },
      'relentless-grasp': {
        name: 'Grapa Implacable',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'La grapa del vampir esdevé impossiblement forta: un cop s\'aferra a alguna cosa, només es deixa anar desmembrant-lo. Suma la seva puntuació de Potència com a èxits automàtics a qualsevol intent d\'agafar-se o de mantenir una presa, tot i que no a la presa inicial.',
      },
      wrecker: {
        name: 'Desballestador',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'La del Poder base',
        description: 'Aplica una força violenta i indiscriminada contra un objecte estàtic per trencar-lo, aixafar-lo i destruir-lo. El temps que exigeix reunir aquesta força el fa inútil en una baralla, però obre portes, immobilitza cotxes i fa exemples d\'estàtues. Requereix Bravura.',
      },
      'crash-down': {
        name: 'Esfondrament',
        cost: '1 Enardiment',
        dicePool: 'Força + Potència',
        duration: 'N/A',
        description: 'El vampir clava l\'aterratge de Salt Vertiginós a lo gran: s\'atura de manera imparable en un punt i fa mal a qualsevol que sigui a prop o a sota d\'on cau. Requereix Salt Vertiginós.',
      },
      'subtle-hammer': {
        name: 'Martell Subtil',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Cada part del cos del vampir projecta la suma de la seva força: un cop de dit transmet el poder d’un cop de puny sencer i la punta d’un dit del peu parteix el ciment. No el fa més fort, sinó capaç d’usar la seva força amb una precisió inhumana: els atacs sense armes i les proeses de força passen a ser accions secundàries de dos daus, una per torn.',
      },
    },
  },

  // ── PRESÈNCIA ────────────────────────────────────────────────────────────────
  presence: {
    name: 'Presència',
    description: 'La Presència és una Disciplina que expressa l\'existència bipolar del vampir. Serveix per atraure les víctimes o dispersar-les aterrides. Permet el control de multituds, la manipulació emocional i la devoció forçada. La Presència afecta les emocions dels que hi són subjectes, no les ments.',
    tipo: 'Mental',
    amenaza: 'Baixa-Mitjana. En ser un poder subtil, la gent rarament s\'adona que ha estat afectada per Presència.',
    resonancia: 'Sanguínia. Els bells i luxuriosos, aquells completament enamorats del vampir, models, actors i estrelles de cinema, oradors públics i privats convincents, estrelles de YouTube i influencers d\'Instagram.',
    clanes: ['Brujah', 'El Ministeri', 'Ravnos', 'Toreador', 'Ventrue'],
    powers: {
      daunt: {
        name: 'Atemorir',
        cost: 'Cap',
        dicePool: 'Carisma + Presència contra Compostura + Resolució',
        duration: 'Una escena',
        description: 'Afegeix el valor de Presència a qualsevol tirada d\'Intimidació. Atacar l\'usuari requereix una tirada de Resolució + Compostura dif. 2. Fascinació i Atemorir no es poden usar alhora.',
      },
      awe: {
        name: 'Fascinació',
        cost: 'Cap',
        dicePool: 'Manipulació + Presència contra Compostura + Intel·ligència',
        duration: 'Una escena',
        description: 'Afegeix Presència a tirades de Persuasió, Interpretació i altres de Carisma. Qui noti l\'efecte pot resistir amb contesa Compostura + Intel·ligència. Victòria = immune una escena; crítica = immune tota la nit. Els efectes de Presència no s\'acumulen.',
      },
      'lingering-kiss': {
        name: 'Bes Persistent',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Fins a resistir-la',
        description: 'Els mortals alimentats esdevenen addictes al Bes. Afegeix el valor de Presència com a daus extra a qualsevol tirada de Carisma posterior contra la víctima mossegada. Pot provocar anèmia, autolesió o mort per addicció. Prova de Força de Voluntat dif. = Presència setmanal per resistir (3 setmanes seguides trenca l\'efecte).',
      },
      entrancement: {
        name: 'Encantament',
        cost: '1 Enardiment',
        dicePool: 'Carisma + Presència contra Compostura + Astúcia',
        duration: 'Una hora (+1 per marge)',
        description: 'Enfoca l\'encant en una persona (similar a enamorament). L\'usuari suma Presència a qualsevol reserva Social contra el subjecte encantat. Peticions que danyin el subjecte o els seus éssers estimats exigeixen una contesa; una fallada acaba l\'efecte i l\'immunitza la resta de la nit.',
      },
      'dread-gaze': {
        name: 'Mirada Aterridora',
        cost: '1 Enardiment',
        dicePool: 'Carisma + Presència contra Compostura + Resolució',
        duration: 'Un torn',
        description: 'Fallada: mortals només defensa pròpia un torn; vampirs no afectats. Victòria: mortals fugen; vampirs només defensa pròpia (o gasten Força de Voluntat = marge). Victòria crítica: mortals paralitzats o en posició fetal; vampirs fan Frenesí de terror dif. 3.',
      },
      summon: {
        name: 'Invocació',
        cost: '1 Enardiment',
        dicePool: 'Manipulació + Presència contra Compostura + Intel·ligència',
        duration: 'Una nit',
        description: 'Convoca algú sobre qui hagi usat Fascinació, Encantament, Majestat o que hagi tastat la seva Sang. L\'objectiu sap qui el convoca i on és. Victòria = pot acudir o no; crítica = arriba al més ràpid possible tret de risc immediat. No es posarà en perill físic o financer.',
      },
      'irresistible-voice': {
        name: 'Veu Irresistible',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'Basta que s\'escolti la veu de l\'usuari per aplicar Poders de Dominació. No funciona a través de mitjans electrònics (telèfon, TV, intercomunicadors).',
        amalgama: 'Dominació 1',
      },
      'star-magnetism': {
        name: 'Magnetisme d\'Estrella',
        cost: '+1 Enardiment (sobre el Poder base)',
        dicePool: 'N/A',
        duration: 'La del Poder base',
        description: 'Fascinació, Atemorir i Encantament poden transmetre\'s per transmissions en directe (no gravacions). Si es fa servir Encantament, cal pronunciar el nom de la víctima amb claredat (afecta a una persona). Els altres el perceben com a encantador, però no sobrenaturalment.',
      },
      majesty: {
        name: 'Majestat',
        cost: '2 Enardiments',
        dicePool: 'Carisma + Presència contra Compostura + Resolució',
        duration: 'Una escena',
        description: 'Els presents només poden mirar-lo bocabadats o desviar la mirada amb por/submissió. Actuar contra l\'usuari (excepte per supervivència) requereix contesa Compostura + Resolució contra Carisma + Presència. Victòria = un torn lliure per punt de marge; només la victòria crítica resisteix tota l\'escena.',
      },
      'eyes-of-the-serpent': {
        name: 'Ulls de la Serp',
        cost: 'Cap',
        dicePool: 'Carisma + Presència contra Astúcia + Compostura',
        duration: 'Una escena (o fins a trencar el contacte)',
        description: 'Els ulls del vampir esdevenen orbes esquinçats de serp i congelen al lloc el mortal que li sostingui la mirada. També pot hipnotitzar així altres vampirs, però l\'efecte és fugaç i és probable que desperti la ira de la víctima.',
        amalgama: 'Protean 1',
      },
      melpominee: {
        name: 'Melpòmene',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'N/A',
        description: 'La veu de l\'usuari es converteix en la d\'una sirena, capaç d\'embadalir o aterrir tota sola. Pot aplicar Atemorir, Encantament, Fascinació, Majestat i Mirada Aterridora sense veure l\'objectiu, que només cal que sigui prou a prop per sentir-lo. No conserva el seu efecte gravada ni transmesa.',
      },
      'thrown-voice': {
        name: 'Veu Llançada',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'La veu del vampir emana de qualsevol punt a la vista, com a xiuxiueig o com a crit, i sona com si ell fos allà. També pot deixar-la en un lloc perquè continuï seduint o aterrint qui atregui, segons el Poder que l\'acompanyi.',
        amalgama: 'Auspex 1',
      },
      'suffuse-the-edifice': {
        name: 'Cobrir l\'Edifici',
        cost: 'El del Poder base',
        dicePool: 'Com el Poder base (Fascinació, Atemorir o Majestat)',
        duration: 'La del Poder base',
        description: 'Mentre és dins d\'un edifici o lloc semblant, el vampir estén Fascinació, Atemorir i Majestat a l\'estructura mateixa. Qualsevol que hi sigui a dins o l\'observi des de fora reacciona a l\'edifici com si el mateix vampir hi fos present.',
      },
    },
  },

  // ── PROTEAN ──────────────────────────────────────────────────────────────────
  protean: {
    name: 'Protean',
    description: 'El poder de mutar, canviar de forma i esdevenir depredadors cada cop més letals és tan natural per al vampir com ho és per al Lupí. Els practicants de Protean utilitzen la Disciplina per la seva utilitat: convertir-se en una bèstia, transformar els seus membres en armes o canviar de forma per evadir la captura.',
    tipo: 'Físic',
    amenaza: 'Alta. Tots els Poders de Protean, una de les Disciplines més descarades dels vampirs, poden violar la Mascarada per si mateixos.',
    resonancia: 'Sang animal, especialment d\'aquells que coincideixen amb la forma adoptada; la sang d\'homes llop, changelings i altres quimeres sobrenaturals d\'homes i bèsties.',
    clanes: ['El Ministeri', 'Gangrel', 'Tzimisce'],
    powers: {
      'eyes-of-the-beast': {
        name: 'Ulls de la Bèstia',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'A voluntat',
        description: 'Els ulls brillen vermells. Ignora qualsevol penalització a la visió per foscor, fins i tot sobrenatural. L\'aparença inhumana atorga +2 daus a la reserva d\'Intimidació contra mortals.',
      },
      'weight-of-the-feather': {
        name: 'Pes de la Ploma',
        cost: 'Cap',
        dicePool: 'Astúcia + Supervivència',
        duration: 'A voluntat',
        description: 'Redueix la seva massa efectiva. Immune al dany per caigudes, col·lisions i ser llançat; no activa sensors de pressió. La força es redueix proporcionalment (no serveix per salts més llargs). Si és reactiu (caiguda sobtada), tirada a dificultat 3.',
      },
      'feral-weapons': {
        name: 'Armes Salvatges',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Estén les seves armes naturals (ungles a urpes, ullals a dagues). +2 al dany de Baralla; agreujat contra mortals i superficial —no reduït a la meitat— contra vampirs.',
      },
      shapechange: {
        name: 'Canviar de Forma',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Es transforma en un animal de massa similar (típicament llop, felí gran o serp gegant) associat al Clan. La transformació dura un torn sense poder fer res més. Adquireix Atributs Físics, sentits i Habilitats de l\'animal, i els seus límits naturals.',
      },
      'earth-meld': {
        name: 'Fusió amb la Terra',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Un dia o més',
        description: 'S\'enfonsa en superfície natural (roca, terra nua, herba) — no funciona en formigó ni asfalt. Triga un torn; deixa els objectes transportats a la superfície. És conscient del seu entorn tret durant el son diürn. Puja la nit següent tret Letargia.',
      },
      metamorphosis: {
        name: 'Metamorfosi',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: '(Prerequisit: Canviar de Forma) Atorga una forma animal addicional (ratpenat, rata, insectes inusualment grans o serps) i permet canviar la mida.',
      },
      'the-unfettered-heart': {
        name: 'Cor Alliberat',
        cost: 'Cap',
        dicePool: 'N/A',
        duration: 'Passiva',
        description: 'El cor es mou lliurement dins del pit. +3 a la dificultat per estacar fora de combat; en combat cos a cos, l\'estaca només penetra amb victòria crítica. Si és estacat, pot tirar Força + Resolució dif. 5 un cop per hora per expulsar-la (impossible amb Ànsia 5).',
      },
      'mist-form': {
        name: 'Forma de Boira',
        cost: '1-3 Enardiments',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Es converteix en boira intangible: travessa canonades, escletxes i esquerdes. La transformació dura 3 torns (accelerable amb Enardiments extra, un per torn). Es mou a velocitat de passeig; no pot parlar, atacar ni usar la majoria de Disciplines. Només vulnerable a llum solar, foc i atacs sobrenaturals immaterials.',
      },
      vicissitude: {
        name: 'Vicissitud',
        cost: '1 Enardiment',
        dicePool: 'Resolució + Protean',
        duration: 'Permanent',
        description: 'El vampir exigeix obediència a la seva pròpia carn: pell, múscul i os poden esculpir-se o recargolar-se en altres formes, des d’eines corporals útils fins a ornaments expressius. El resultat de vegades és desconcertantment bell i d’altres només monstruós, i les transformacions majors cobren un altíssim preu al seu físic.',
        amalgama: 'Dominació 2',
      },
      fleshcrafting: {
        name: 'Modelar Carn',
        cost: '1 Enardiment',
        dicePool: 'Resolució + Protean contra Resistència + Resolució',
        duration: 'Permanent',
        description: 'Amplia el domini sobre la carn als cossos aliens. És un Poder temut amb raó, perquè molts dels qui l\'usen tenen fama de torturadors inhumans, tot i que d\'altres l\'empren amb gran efecte per millorar i adaptar els seus servents i aliats. Requereix Vicissitud.',
        amalgama: 'Dominació 2',
      },
      'horrid-form': {
        name: 'Forma Horrenda',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir assumeix una forma veritablement monstruosa, amb urpes terribles, ullals prominents i músculs nerviüts: la seva Bèstia feta carn, gairebé sempre la mateixa cada vegada. Activar-la porta un torn sencer, durant el qual només pot defensar-se amb les seves reserves prèvies. Requereix Vicissitud.',
        amalgama: 'Dominació 2',
      },
      'one-with-the-land': {
        name: 'U amb la Terra',
        cost: '2 Enardiments',
        dicePool: 'N/A',
        duration: 'Un dia o més',
        description: 'Com Fusió amb la Terra, però sense que el limiti la composició de la superfície on descansa: hi ha vampirs que s’introdueixen als murs de les seves hisendes. A més, manté una consciència preternatural del que passa al domini. Requereix Fusió amb la Terra.',
        amalgama: 'Animalisme 2',
      },
    },
  },

  // ── BRUIXERIA DE SANG ────────────────────────────────────────────────────────
  'blood-sorcery': {
    name: 'Bruixeria de Sang',
    description: 'També anomenada Taumatúrgia (pels Tremere) o Quietus/Extinció (pels Banu Haqim). A diferència d\'altres Disciplines, els practicants de Bruixeria de Sang requereixen professors. Confereix Poders i desbloqueja la capacitat de realitzar rituals fins al nivell de l\'usuari en la Disciplina.',
    tipo: '',
    amenaza: 'Baixa-alta. L\'aparença individual dels Poders i rituals de Bruixeria de Sang varia tant com els seus efectes.',
    resonancia: 'Sanguínia. Encara que no és inherent a la Sang en si mateixa, la Bruixeria de Sang respon amb entusiasme a la sang d\'ocultistes humans, bruixots i líders de sectes, així com a hemofílics i bibliòfils.',
    powers: {
      'a-taste-for-blood': {
        name: 'Gust de la Sang',
        cost: 'Cap',
        dicePool: 'Resolució + Bruixeria de Sang',
        duration: 'N/A',
        description: 'En tastar una gota, identifica la Ressonància i intensitat (si és humana), si pertany a un mortal, Ghoul, vampir o altre sobrenatural, i la Potència de Sang relativa (per tant, el marge probable de Generació). Una crítica també revela si ha comès Diablerie i la Generació exacta (±1).',
      },
      'corrosive-vitae': {
        name: 'Vitae Corrosiva',
        cost: '1+ Enardiment',
        dicePool: 'Resolució + Bruixeria de Sang (per controlar la corrosió amb precisió)',
        duration: 'N/A',
        description: 'Altera la seva Sang fent-la corrosiva al contacte amb materials morts: dissol roba, fusta, metall, panys o grillons. L\'Ànsia gastada determina la potència de l\'àcid.',
      },
      'extinguish-vitae': {
        name: 'Extingir Vitae',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Bruixeria de Sang contra Resistència + Compostura',
        duration: 'N/A',
        description: 'Contesa contra un vampir en la seva línia de visió mentre es concentra un torn. Victòria = +1 a l\'Ànsia de l\'objectiu; victòria crítica = +2. Si la víctima veu l\'usuari, pot identificar-lo amb Intel·ligència + Ocultisme contra Astúcia + Subterfugi.',
      },
      'blood-of-potency': {
        name: 'Sang de Potència',
        cost: '1 Enardiment',
        dicePool: 'Resolució + Bruixeria de Sang',
        duration: 'Escena o nit',
        description: 'Tirada Resolució + Bruixeria de Sang dif. 2 + Potència de Sang actual. Victòria = +1 Potència de Sang aquesta escena; victòria crítica = +2. Permet superar el límit de Potència per Generació mentre duri.',
      },
      'scorpions-touch': {
        name: 'Toc d\'Escorpí',
        cost: '1+ Enardiment',
        dicePool: 'Força + Bruixeria de Sang contra Resistència + Ocultisme o Fortalesa',
        duration: 'Una escena',
        description: 'Cada Enardiment cobreix una arma cos a cos o permet escopir. Si impacta, contesa Força + Bruixeria de Sang contra Resistència + Ocultisme (o Fortalesa). Dany = marge: agreujat a mortals, superficial no reduït a vampirs. Un mortal amb ni tan sols 1 punt cau inconscient.',
      },
      'theft-of-vitae': {
        name: 'Robatori de Vitae',
        cost: '1 Enardiment',
        dicePool: 'Astúcia + Bruixeria de Sang contra Astúcia + Ocultisme',
        duration: 'Una alimentació',
        description: 'Obre una ferida en un mortal a distància; la sang surt disparada cap a la boca de l\'usuari. S\'alimenta al doble de velocitat (triple amb victòria crítica). No pot fer res més mentre duri. L\'armadura no protegeix (la víctima es dessagna dins del vestit). La ferida es tanca en acabar.',
      },
      'cauldron-of-blood': {
        name: 'Calder de Sang',
        cost: '1 Enardiment (i 1+ Màcula)',
        dicePool: 'Resolució + Bruixeria de Sang contra Compostura + Ocultisme o Fortalesa',
        duration: 'Un torn',
        description: 'Requereix tocar la víctima. Contesa Resolució + Bruixeria de Sang contra Compostura + Ocultisme (o Fortalesa). Cada punt de marge causa 1 punt de dany agreujat. Un mortal amb almenys 1 punt mor entre crits. Un vampir afegeix 1 Ànsia per punt de dany fins arribar a Ànsia 5.',
      },
      'baals-caress': {
        name: 'Carícia de Baal',
        cost: '1+ Enardiment',
        dicePool: 'Força + Bruixeria de Sang contra Resistència + Ocultisme o Fortalesa',
        duration: 'Una escena',
        description: 'Com Toc d\'Escorpí però letal: si impacta, cada punt de marge causa dany agreujat a mortals i vampirs per igual. Un mortal amb ni tan sols 1 punt mor a l\'instant. Si un vampir pateix agreujat, tirada de nou — victòria = Letargia en anar a dormir.',
      },
      'track-secrets': {
        name: 'Rastrejar Secrets',
        cost: '1 Enardiment',
        dicePool: 'Intel·ligència + Bruixeria de Sang',
        duration: 'Una nit',
        description: 'El bruixot deslliga rierols de la seva Sang que busquen informació sobre un tema de la seva elecció, cosa que li permet rastrejar biblioteques senceres en qüestió de minuts. El que s\'ha investigat queda després amb una delatora taca de sang.',
      },
      'blood-aegis': {
        name: 'Ègida de Sang',
        cost: '1+ Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'El vampir obliga la seva Vitae a formar una barrera protectora: una tremolosa capa de Sang que es mou tota sola per interceptar els projectils que s\'acosten. Cada Enardiment gastat redueix en 5 el dany dels atacs a distància, fins a esgotar-se.',
      },
    },
  },

  // ── ALQUÍMIA DE SANG FEBLE ───────────────────────────────────────────────────
  'thin-blood-alchemy': {
    name: 'Alquímia de Sang Feble',
    description: 'La Sang Feble de les últimes Generacions gairebé no té poder propi, però certs Sang Feble han après a usar-la com a catalitzador. Barrejant sang humana fortament ressonant i de vegades altres substàncies amb la seva pròpia Vitae, els alquimistes poden simular una àmplia gamma de Poders d\'altres Disciplines i crear alguns Poders únics propis. L\'Alquímia pot simular alguns Poders de Bruixeria de Sang, però no rituals.',
    tipo: '',
    amenaza: 'Varia segons els Poders que imita i el mètode utilitzat.',
    resonancia: 'La necessària per a cada fórmula, per la qual cosa varia en conseqüència.',
    clanes: ['Sang Feble'],
    powers: {
      'far-reach': {
        name: 'Abast Llunyà',
        cost: '1 Enardiment',
        dicePool: 'Resolució + Alquímia contra Força + Atletisme',
        duration: 'Un torn (o sostingut)',
        description: 'Aixeca, empeny o estira un objecte o persona <100 kg a <10 m a la vista. Objectes fràgils poden trencar-se. Ganivets manejables amb Resolució + Alquímia (−2 daus), +1 dany. Contra subjecte resistent, contesa; amb victòria, llançar-lo 1 m per marge, dany superficial. Sostenir flotant requereix tirada dif. 3 cada torn.',
      },
      'profane-hieros-gamos': {
        name: 'Hieros Gamos Profà',
        cost: '1 Enardiment (destil·lació)',
        dicePool: 'Resistència/Manipulació/Intel·ligència + Alquímia (segons mètode)',
        duration: 'Permanent',
        description: 'Permet canviar de sexe biològic aprofitant la naturalesa fluida de la condició de Sang Feble. El procés triga hores i requereix destil·lació.',
      },
      haze: {
        name: 'Boirina',
        cost: '1 Enardiment',
        dicePool: 'N/A',
        duration: 'Una escena',
        description: 'Núvol de vapor al voltant de l\'alquimista que oculta trets i enfosqueix la silueta. Qui intenti identificar-lo o colpejar-lo amb armes a distància pateix −2 daus. Pot estendre\'s a un grup de fins a 5 persones gastant un altre Enardiment.',
      },
      envelop: {
        name: 'Envoltar',
        cost: '1 Enardiment',
        dicePool: 'Astúcia + Alquímia contra Resistència + Supervivència',
        duration: 'Una escena',
        description: 'La boira s\'arremolina al voltant d\'un objectiu a la vista: −3 daus a detecció visual i atacs a distància. A més, contra un mortal, contesa Astúcia + Alquímia contra Resistència + Supervivència: victòria = només pot tossir sense actuar; victòria crítica = perd la consciència. Un sol objectiu alhora.',
      },
      defractionate: {
        name: 'Defraccionar',
        cost: '1 Enardiment (destil·lació)',
        dicePool: 'Resistència/Manipulació/Intel·ligència + Alquímia (segons mètode)',
        duration: 'N/A',
        description: 'Elixir que renova la sang mèdica fraccionada, permetent alimentar-se a vampirs sense el Mèrit Gorja de Ferro. Cada èxit en la destil·lació converteix una bossa (sacia 1 Ànsia).',
      },
      'aerial-impulse': {
        name: 'Ímpetu Aeri',
        cost: '1 Enardiment',
        dicePool: 'Força + Alquímia contra Força + Atletisme (si es resisteix)',
        duration: 'Una escena',
        description: 'Vola o es mou a velocitat de carrera en qualsevol direcció. Carregar un humà redueix la velocitat a pas normal. Agafar i carregar un subjecte involuntari o tombar un volador requereix contesa Força + Alquímia contra Força + Atletisme.',
      },
      'awaken-the-sleeper': {
        name: 'Despertar l\'Adormit',
        cost: '1 Enardiment (destil·lació)',
        dicePool: 'Resistència/Manipulació/Intel·ligència + Alquímia (segons mètode)',
        duration: 'N/A',
        description: 'Elixir barrejat amb sang humana que desperta un vampir en Letargia. Cada èxit per sobre de 2 en la destil·lació permet despertar un vampir amb Potència de Sang = (èxits − 2) o menys.',
      },
    },
  },
}
